[package]
name = "bishoperic-aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
dotenvy = "0.15.7"
reqwest = { version = "0.12.23", features = ["blocking"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
